export const naicsSelectOptions = [
  {value: '111110', name: 'Soybean Farming'},
  {value: '111120', name: 'Oilseed (except Soybean) Farming'},
  {value: '111130', name: 'Dry Pea and Bean Farming'},
  {value: '111140', name: 'Wheat Farming'},
  {value: '111150', name: 'Corn Farming'},
  {value: '111160', name: 'Rice Farming'},
  {value: '111191', name: 'Oilseed and Grain Combination Farming'},
  {value: '111199', name: 'All Other Grain Farming'},
  {value: '111211', name: 'Potato Farming'},
  {value: '111219', name: 'Other Vegetable (except Potato) and Melon Farming'},
  {value: '111310', name: 'Orange Groves'},
  {value: '111320', name: 'Citrus (except Orange) Groves'},
  {value: '111331', name: 'Apple Orchards'},
  {value: '111332', name: 'Grape Vineyards'},
  {value: '111333', name: 'Strawberry Farming'},
  {value: '111334', name: 'Berry (except Strawberry) Farming'},
  {value: '111335', name: 'Tree Nut Farming'},
  {value: '111336', name: 'Fruit and Tree Nut Combination Farming'},
  {value: '111339', name: 'Other Noncitrus Fruit Farming'},
  {value: '111411', name: 'Mushroom Production'},
  {value: '111419', name: 'Other Food Crops Grown Under Cover'},
  {value: '111421', name: 'Nursery and Tree Production'},
  {value: '111422', name: 'Floriculture Production'},
  {value: '111910', name: 'Tobacco Farming'},
  {value: '111920', name: 'Cotton Farming'},
  {value: '111930', name: 'Sugarcane Farming'},
  {value: '111940', name: 'Hay Farming'},
  {value: '111991', name: 'Sugar Beet Farming'},
  {value: '111992', name: 'Peanut Farming'},
  {value: '111998', name: 'All Other Miscellaneous Crop Farming'},
  {value: '112111', name: 'Beef Cattle Ranching and Farming'},
  {value: '112112', name: 'Cattle Feedlots'},
  {value: '112120', name: 'Dairy Cattle and Milk Production'},
  {value: '112130', name: 'Dual-Purpose Cattle Ranching and Farming'},
  {value: '112210', name: 'Hog and Pig Farming'},
  {value: '112310', name: 'Chicken Egg Production'},
  {value: '112320', name: 'Broilers and Other Meat Type Chicken Production'},
  {value: '112330', name: 'Turkey Production'},
  {value: '112340', name: 'Poultry Hatcheries'},
  {value: '112390', name: 'Other Poultry Production'},
  {value: '112410', name: 'Sheep Farming'},
  {value: '112420', name: 'Goat Farming'},
  {value: '112511', name: 'Finfish Farming and Fish Hatcheries'},
  {value: '112512', name: 'Shellfish Farming'},
  {value: '112519', name: 'Other Aquaculture'},
  {value: '112910', name: 'Apiculture'},
  {value: '112920', name: 'Horses and Other Equine Production'},
  {value: '112930', name: 'Fur-Bearing Animal and Rabbit Production'},
  {value: '112990', name: 'All Other Animal Production'},
  {value: '113110', name: 'Timber Tract Operations'},
  {value: '113210', name: 'Forest Nurseries and Gathering of Forest Products'},
  {value: '113310', name: 'Logging'},
  {value: '114111', name: 'Finfish Fishing'},
  {value: '114112', name: 'Shellfish Fishing'},
  {value: '114119', name: 'Other Marine Fishing'},
  {value: '114210', name: 'Hunting and Trapping'},
  {value: '115111', name: 'Cotton Ginning'},
  {value: '115112', name: 'Soil Preparation, Planting, and Cultivating '},
  {value: '115113', name: 'Crop Harvesting, Primarily by Machine '},
  {value: '115114', name: 'Postharvest Crop Activities (except Cotton Ginning)'},
  {value: '115115', name: 'Farm Labor Contractors and Crew Leaders'},
  {value: '115116', name: 'Farm Management Services'},
  {value: '115210', name: 'Support Activities for Animal Production'},
  {value: '115310', name: 'Support Activities for Forestry'},
  {value: '211120', name: 'Crude Petroleum Extraction '},
  {value: '211130', name: 'Natural Gas Extraction'},
  {value: '212111', name: 'Bituminous Coal and Lignite Surface Mining'},
  {value: '212112', name: 'Bituminous Coal Underground Mining'},
  {value: '212113', name: 'Anthracite Mining'},
  {value: '212210', name: 'Iron Ore Mining'},
  {value: '212221', name: 'Gold Ore Mining'},
  {value: '212222', name: 'Silver Ore Mining'},
  {value: '212230', name: 'Copper, Nickel, Lead, and Zinc Mining '},
  {value: '212291', name: 'Uranium-Radium-Vanadium Ore Mining'},
  {value: '212299', name: 'All Other Metal Ore Mining'},
  {value: '212311', name: 'Dimension Stone Mining and Quarrying'},
  {value: '212312', name: 'Crushed and Broken Limestone Mining and Quarrying'},
  {value: '212313', name: 'Crushed and Broken Granite Mining and Quarrying'},
  {value: '212319', name: 'Other Crushed and Broken Stone Mining and Quarrying'},
  {value: '212321', name: 'Construction Sand and Gravel Mining'},
  {value: '212322', name: 'Industrial Sand Mining'},
  {value: '212324', name: 'Kaolin and Ball Clay Mining'},
  {value: '212325', name: 'Clay and Ceramic and Refractory Minerals Mining'},
  {value: '212391', name: 'Potash, Soda, and Borate Mineral Mining '},
  {value: '212392', name: 'Phosphate Rock Mining'},
  {value: '212393', name: 'Other Chemical and Fertilizer Mineral Mining'},
  {value: '212399', name: 'All Other Nonmetallic Mineral Mining'},
  {value: '213111', name: 'Drilling Oil and Gas Wells'},
  {value: '213112', name: 'Support Activities for Oil and Gas Operations'},
  {value: '213113', name: 'Support Activities for Coal Mining'},
  {value: '213114', name: 'Support Activities for Metal Mining'},
  {value: '213115', name: 'Support Activities for Nonmetallic Minerals (except Fuels) Mining'},
  {value: '221111', name: 'Hydroelectric Power Generation'},
  {value: '221112', name: 'Fossil Fuel Electric Power Generation'},
  {value: '221113', name: 'Nuclear Electric Power Generation'},
  {value: '221114', name: 'Solar Electric Power Generation'},
  {value: '221115', name: 'Wind Electric Power Generation'},
  {value: '221116', name: 'Geothermal Electric Power Generation'},
  {value: '221117', name: 'Biomass Electric Power Generation'},
  {value: '221118', name: 'Other Electric Power Generation'},
  {value: '221121', name: 'Electric Bulk Power Transmission and Control'},
  {value: '221122', name: 'Electric Power Distribution'},
  {value: '221210', name: 'Natural Gas Distribution'},
  {value: '221310', name: 'Water Supply and Irrigation Systems'},
  {value: '221320', name: 'Sewage Treatment Facilities'},
  {value: '221330', name: 'Steam and Air-Conditioning Supply'},
  {value: '236115', name: 'New Single-Family Housing Construction (except For-Sale Builders)'},
  {value: '236116', name: 'New Multifamily Housing Construction (except For-Sale Builders)'},
  {value: '236117', name: 'New Housing For-Sale Builders'},
  {value: '236118', name: 'Residential Remodelers'},
  {value: '236210', name: 'Industrial Building Construction'},
  {value: '236220', name: 'Commercial and Institutional Building Construction'},
  {value: '237110', name: 'Water and Sewer Line and Related Structures Construction'},
  {value: '237120', name: 'Oil and Gas Pipeline and Related Structures Construction'},
  {value: '237130', name: 'Power and Communication Line and Related Structures Construction'},
  {value: '237210', name: 'Land Subdivision'},
  {value: '237310', name: 'Highway, Street, and Bridge Construction '},
  {value: '237990', name: 'Other Heavy and Civil Engineering Construction'},
  {value: '238110', name: 'Poured Concrete Foundation and Structure Contractors'},
  {value: '238120', name: 'Structural Steel and Precast Concrete Contractors'},
  {value: '238130', name: 'Framing Contractors'},
  {value: '238140', name: 'Masonry Contractors'},
  {value: '238150', name: 'Glass and Glazing Contractors'},
  {value: '238160', name: 'Roofing Contractors'},
  {value: '238170', name: 'Siding Contractors'},
  {value: '238190', name: 'Other Foundation, Structure, and Building Exterior Contractors '},
  {value: '238210', name: 'Electrical Contractors and Other Wiring Installation Contractors'},
  {value: '238220', name: 'Plumbing, Heating, and Air-Conditioning Contractors '},
  {value: '238290', name: 'Other Building Equipment Contractors'},
  {value: '238310', name: 'Drywall and Insulation Contractors'},
  {value: '238320', name: 'Painting and Wall Covering Contractors'},
  {value: '238330', name: 'Flooring Contractors'},
  {value: '238340', name: 'Tile and Terrazzo Contractors'},
  {value: '238350', name: 'Finish Carpentry Contractors'},
  {value: '238390', name: 'Other Building Finishing Contractors'},
  {value: '238910', name: 'Site Preparation Contractors'},
  {value: '238990', name: 'All Other Specialty Trade Contractors'},
  {value: '311111', name: 'Dog and Cat Food Manufacturing'},
  {value: '311119', name: 'Other Animal Food Manufacturing'},
  {value: '311211', name: 'Flour Milling'},
  {value: '311212', name: 'Rice Milling'},
  {value: '311213', name: 'Malt Manufacturing'},
  {value: '311221', name: 'Wet Corn Milling'},
  {value: '311224', name: 'Soybean and Other Oilseed Processing'},
  {value: '311225', name: 'Fats and Oils Refining and Blending'},
  {value: '311230', name: 'Breakfast Cereal Manufacturing'},
  {value: '311313', name: 'Beet Sugar Manufacturing'},
  {value: '311314', name: 'Cane Sugar Manufacturing'},
  {value: '311340', name: 'Nonchocolate Confectionery Manufacturing'},
  {value: '311351', name: 'Chocolate and Confectionery Manufacturing from Cacao Beans'},
  {value: '311352', name: 'Confectionery Manufacturing from Purchased Chocolate'},
  {value: '311411', name: 'Frozen Fruit, Juice, and Vegetable Manufacturing '},
  {value: '311412', name: 'Frozen Specialty Food Manufacturing'},
  {value: '311421', name: 'Fruit and Vegetable Canning'},
  {value: '311422', name: 'Specialty Canning'},
  {value: '311423', name: 'Dried and Dehydrated Food Manufacturing'},
  {value: '311511', name: 'Fluid Milk Manufacturing'},
  {value: '311512', name: 'Creamery Butter Manufacturing'},
  {value: '311513', name: 'Cheese Manufacturing'},
  {value: '311514', name: 'Dry, Condensed, and Evaporated Dairy Product Manufacturing '},
  {value: '311520', name: 'Ice Cream and Frozen Dessert Manufacturing'},
  {value: '311611', name: 'Animal (except Poultry) Slaughtering'},
  {value: '311612', name: 'Meat Processed from Carcasses'},
  {value: '311613', name: 'Rendering and Meat Byproduct Processing'},
  {value: '311615', name: 'Poultry Processing'},
  {value: '311710', name: 'Seafood Product Preparation and Packaging'},
  {value: '311811', name: 'Retail Bakeries'},
  {value: '311812', name: 'Commercial Bakeries'},
  {value: '311813', name: 'Frozen Cakes, Pies, and Other Pastries Manufacturing '},
  {value: '311821', name: 'Cookie and Cracker Manufacturing'},
  {value: '311824', name: 'Dry Pasta, Dough, and Flour Mixes Manufacturing from Purchased Flour '},
  {value: '311830', name: 'Tortilla Manufacturing'},
  {value: '311911', name: 'Roasted Nuts and Peanut Butter Manufacturing'},
  {value: '311919', name: 'Other Snack Food Manufacturing'},
  {value: '311920', name: 'Coffee and Tea Manufacturing'},
  {value: '311930', name: 'Flavoring Syrup and Concentrate Manufacturing'},
  {value: '311941', name: 'Mayonnaise, Dressing, and Other Prepared Sauce Manufacturing '},
  {value: '311942', name: 'Spice and Extract Manufacturing'},
  {value: '311991', name: 'Perishable Prepared Food Manufacturing'},
  {value: '311999', name: 'All Other Miscellaneous Food Manufacturing'},
  {value: '312111', name: 'Soft Drink Manufacturing'},
  {value: '312112', name: 'Bottled Water Manufacturing'},
  {value: '312113', name: 'Ice Manufacturing'},
  {value: '312120', name: 'Breweries'},
  {value: '312130', name: 'Wineries'},
  {value: '312140', name: 'Distilleries'},
  {value: '312230', name: 'Tobacco Manufacturing'},
  {value: '313110', name: 'Fiber, Yarn, and Thread Mills '},
  {value: '313210', name: 'Broadwoven Fabric Mills'},
  {value: '313220', name: 'Narrow Fabric Mills and Schiffli Machine Embroidery'},
  {value: '313230', name: 'Nonwoven Fabric Mills'},
  {value: '313240', name: 'Knit Fabric Mills'},
  {value: '313310', name: 'Textile and Fabric Finishing Mills'},
  {value: '313320', name: 'Fabric Coating Mills'},
  {value: '314110', name: 'Carpet and Rug Mills'},
  {value: '314120', name: 'Curtain and Linen Mills'},
  {value: '314910', name: 'Textile Bag and Canvas Mills'},
  {value: '314994', name: 'Rope, Cordage, Twine, Tire Cord, and Tire Fabric Mills '},
  {value: '314999', name: 'All Other Miscellaneous Textile Product Mills'},
  {value: '315110', name: 'Hosiery and Sock Mills'},
  {value: '315190', name: 'Other Apparel Knitting Mills'},
  {value: '315210', name: 'Cut and Sew Apparel Contractors'},
  {value: '315220', name: 'Men’s and Boys’ Cut and Sew Apparel Manufacturing'},
  {value: '315240', name: 'Women’s, Girls’, and Infants’ Cut and Sew Apparel Manufacturing '},
  {value: '315280', name: 'Other Cut and Sew Apparel Manufacturing'},
  {value: '315990', name: 'Apparel Accessories and Other Apparel Manufacturing'},
  {value: '316110', name: 'Leather and Hide Tanning and Finishing'},
  {value: '316210', name: 'Footwear Manufacturing'},
  {value: '316992', name: 'Women\'s Handbag and Purse Manufacturing'},
  {value: '316998', name: 'All Other Leather Good and Allied Product Manufacturing'},
  {value: '321113', name: 'Sawmills'},
  {value: '321114', name: 'Wood Preservation'},
  {value: '321211', name: 'Hardwood Veneer and Plywood Manufacturing'},
  {value: '321212', name: 'Softwood Veneer and Plywood Manufacturing'},
  {value: '321213', name: 'Engineered Wood Member (except Truss) Manufacturing'},
  {value: '321214', name: 'Truss Manufacturing'},
  {value: '321219', name: 'Reconstituted Wood Product Manufacturing'},
  {value: '321911', name: 'Wood Window and Door Manufacturing'},
  {value: '321912', name: 'Cut Stock, Resawing Lumber, and Planing '},
  {value: '321918', name: 'Other Millwork (including Flooring)'},
  {value: '321920', name: 'Wood Container and Pallet Manufacturing'},
  {value: '321991', name: 'Manufactured Home (Mobile Home) Manufacturing'},
  {value: '321992', name: 'Prefabricated Wood Building Manufacturing'},
  {value: '321999', name: 'All Other Miscellaneous Wood Product Manufacturing'},
  {value: '322110', name: 'Pulp Mills'},
  {value: '322121', name: 'Paper (except Newsprint) Mills'},
  {value: '322122', name: 'Newsprint Mills'},
  {value: '322130', name: 'Paperboard Mills'},
  {value: '322211', name: 'Corrugated and Solid Fiber Box Manufacturing'},
  {value: '322212', name: 'Folding Paperboard Box Manufacturing'},
  {value: '322219', name: 'Other Paperboard Container Manufacturing'},
  {value: '322220', name: 'Paper Bag and Coated and Treated Paper Manufacturing'},
  {value: '322230', name: 'Stationery Product Manufacturing'},
  {value: '322291', name: 'Sanitary Paper Product Manufacturing'},
  {value: '322299', name: 'All Other Converted Paper Product Manufacturing'},
  {value: '323111', name: 'Commercial Printing (except Screen and Books)'},
  {value: '323113', name: 'Commercial Screen Printing'},
  {value: '323117', name: 'Books Printing'},
  {value: '323120', name: 'Support Activities for Printing'},
  {value: '324110', name: 'Petroleum Refineries'},
  {value: '324121', name: 'Asphalt Paving Mixture and Block Manufacturing'},
  {value: '324122', name: 'Asphalt Shingle and Coating Materials Manufacturing'},
  {value: '324191', name: 'Petroleum Lubricating Oil and Grease Manufacturing'},
  {value: '324199', name: 'All Other Petroleum and Coal Products Manufacturing'},
  {value: '325110', name: 'Petrochemical Manufacturing'},
  {value: '325120', name: 'Industrial Gas Manufacturing'},
  {value: '325130', name: 'Synthetic Dye and Pigment Manufacturing'},
  {value: '325180', name: 'Other Basic Inorganic Chemical Manufacturing'},
  {value: '325193', name: 'Ethyl Alcohol Manufacturing'},
  {value: '325194', name: 'Cyclic Crude, Intermediate, and Gum and Wood Chemical Manufacturing '},
  {value: '325199', name: 'All Other Basic Organic Chemical Manufacturing'},
  {value: '325211', name: 'Plastics Material and Resin Manufacturing'},
  {value: '325212', name: 'Synthetic Rubber Manufacturing'},
  {value: '325220', name: 'Artificial and Synthetic Fibers and Filaments Manufacturing'},
  {value: '325311', name: 'Nitrogenous Fertilizer Manufacturing'},
  {value: '325312', name: 'Phosphatic Fertilizer Manufacturing'},
  {value: '325314', name: 'Fertilizer (Mixing Only) Manufacturing'},
  {value: '325320', name: 'Pesticide and Other Agricultural Chemical Manufacturing'},
  {value: '325411', name: 'Medicinal and Botanical Manufacturing'},
  {value: '325412', name: 'Pharmaceutical Preparation Manufacturing'},
  {value: '325413', name: 'In-Vitro Diagnostic Substance Manufacturing'},
  {value: '325414', name: 'Biological Product (except Diagnostic) Manufacturing'},
  {value: '325510', name: 'Paint and Coating Manufacturing'},
  {value: '325520', name: 'Adhesive Manufacturing'},
  {value: '325611', name: 'Soap and Other Detergent Manufacturing'},
  {value: '325612', name: 'Polish and Other Sanitation Good Manufacturing'},
  {value: '325613', name: 'Surface Active Agent Manufacturing'},
  {value: '325620', name: 'Toilet Preparation Manufacturing'},
  {value: '325910', name: 'Printing Ink Manufacturing'},
  {value: '325920', name: 'Explosives Manufacturing'},
  {value: '325991', name: 'Custom Compounding of Purchased Resins'},
  {value: '325992', name: 'Photographic Film, Paper, Plate, and Chemical Manufacturing '},
  {value: '325998', name: 'All Other Miscellaneous Chemical Product and Preparation Manufacturing'},
  {value: '326111', name: 'Plastics Bag and Pouch Manufacturing'},
  {value: '326112', name: 'Plastics Packaging Film and Sheet (including Laminated) Manufacturing'},
  {value: '326113', name: 'Unlaminated Plastics Film and Sheet (except Packaging) Manufacturing'},
  {value: '326121', name: 'Unlaminated Plastics Profile Shape Manufacturing'},
  {value: '326122', name: 'Plastics Pipe and Pipe Fitting Manufacturing'},
  {value: '326130', name: 'Laminated Plastics Plate, Sheet (except Packaging), and Shape Manufacturing'},
  {value: '326140', name: 'Polystyrene Foam Product Manufacturing'},
  {value: '326150', name: 'Urethane and Other Foam Product (except Polystyrene) Manufacturing'},
  {value: '326160', name: 'Plastics Bottle Manufacturing'},
  {value: '326191', name: 'Plastics Plumbing Fixture Manufacturing'},
  {value: '326199', name: 'All Other Plastics Product Manufacturing'},
  {value: '326211', name: 'Tire Manufacturing (except Retreading)'},
  {value: '326212', name: 'Tire Retreading'},
  {value: '326220', name: 'Rubber and Plastics Hoses and Belting Manufacturing'},
  {value: '326291', name: 'Rubber Product Manufacturing for Mechanical Use'},
  {value: '326299', name: 'All Other Rubber Product Manufacturing'},
  {value: '327110', name: 'Pottery, Ceramics, and Plumbing Fixture Manufacturing '},
  {value: '327120', name: 'Clay Building Material and Refractories Manufacturing'},
  {value: '327211', name: 'Flat Glass Manufacturing'},
  {value: '327212', name: 'Other Pressed and Blown Glass and Glassware Manufacturing'},
  {value: '327213', name: 'Glass Container Manufacturing'},
  {value: '327215', name: 'Glass Product Manufacturing Made of Purchased Glass'},
  {value: '327310', name: 'Cement Manufacturing'},
  {value: '327320', name: 'Ready-Mix Concrete Manufacturing'},
  {value: '327331', name: 'Concrete Block and Brick Manufacturing'},
  {value: '327332', name: 'Concrete Pipe Manufacturing'},
  {value: '327390', name: 'Other Concrete Product Manufacturing'},
  {value: '327410', name: 'Lime Manufacturing'},
  {value: '327420', name: 'Gypsum Product Manufacturing'},
  {value: '327910', name: 'Abrasive Product Manufacturing'},
  {value: '327991', name: 'Cut Stone and Stone Product Manufacturing'},
  {value: '327992', name: 'Ground or Treated Mineral and Earth Manufacturing'},
  {value: '327993', name: 'Mineral Wool Manufacturing'},
  {value: '327999', name: 'All Other Miscellaneous Nonmetallic Mineral Product Manufacturing'},
  {value: '331110', name: 'Iron and Steel Mills and Ferroalloy Manufacturing'},
  {value: '331210', name: 'Iron and Steel Pipe and Tube Manufacturing from Purchased Steel'},
  {value: '331221', name: 'Rolled Steel Shape Manufacturing'},
  {value: '331222', name: 'Steel Wire Drawing'},
  {value: '331313', name: 'Alumina Refining and Primary Aluminum Production'},
  {value: '331314', name: 'Secondary Smelting and Alloying of Aluminum'},
  {value: '331315', name: 'Aluminum Sheet, Plate, and Foil Manufacturing '},
  {value: '331318', name: 'Other Aluminum Rolling, Drawing, and Extruding '},
  {value: '331410', name: 'Nonferrous Metal (except Aluminum) Smelting and Refining'},
  {value: '331420', name: 'Copper Rolling, Drawing, Extruding, and Alloying'},
  {value: '331491', name: 'Nonferrous Metal (except Copper and Aluminum) Rolling, Drawing, and Extruding '},
  {value: '331492', name: 'Secondary Smelting, Refining, and Alloying of Nonferrous Metal (except Copper and Aluminum) '},
  {value: '331511', name: 'Iron Foundries'},
  {value: '331512', name: 'Steel Investment Foundries'},
  {value: '331513', name: 'Steel Foundries (except Investment)'},
  {value: '331523', name: 'Nonferrous Metal Die-Casting Foundries'},
  {value: '331524', name: 'Aluminum Foundries (except Die-Casting)'},
  {value: '331529', name: 'Other Nonferrous Metal Foundries (except Die-Casting)'},
  {value: '332111', name: 'Iron and Steel Forging'},
  {value: '332112', name: 'Nonferrous Forging'},
  {value: '332114', name: 'Custom Roll Forming'},
  {value: '332117', name: 'Powder Metallurgy Part Manufacturing'},
  {value: '332119', name: 'Metal Crown, Closure, and Other Metal Stamping (except Automotive) '},
  {value: '332215', name: 'Metal Kitchen Cookware, Utensil, Cutlery, and Flatware (except Precious) Manufacturing '},
  {value: '332216', name: 'Saw Blade and Handtool Manufacturing'},
  {value: '332311', name: 'Prefabricated Metal Building and Component Manufacturing'},
  {value: '332312', name: 'Fabricated Structural Metal Manufacturing'},
  {value: '332313', name: 'Plate Work Manufacturing'},
  {value: '332321', name: 'Metal Window and Door Manufacturing'},
  {value: '332322', name: 'Sheet Metal Work Manufacturing'},
  {value: '332323', name: 'Ornamental and Architectural Metal Work Manufacturing'},
  {value: '332410', name: 'Power Boiler and Heat Exchanger Manufacturing'},
  {value: '332420', name: 'Metal Tank (Heavy Gauge) Manufacturing'},
  {value: '332431', name: 'Metal Can Manufacturing'},
  {value: '332439', name: 'Other Metal Container Manufacturing'},
  {value: '332510', name: 'Hardware Manufacturing'},
  {value: '332613', name: 'Spring Manufacturing'},
  {value: '332618', name: 'Other Fabricated Wire Product Manufacturing'},
  {value: '332710', name: 'Machine Shops'},
  {value: '332721', name: 'Precision Turned Product Manufacturing'},
  {value: '332722', name: 'Bolt, Nut, Screw, Rivet, and Washer Manufacturing '},
  {value: '332811', name: 'Metal Heat Treating'},
  {value: '332812', name: 'Metal Coating, Engraving (except Jewelry and Silverware), and Allied Services to Manufacturers '},
  {value: '332813', name: 'Electroplating, Plating, Polishing, Anodizing, and Coloring '},
  {value: '332911', name: 'Industrial Valve Manufacturing'},
  {value: '332912', name: 'Fluid Power Valve and Hose Fitting Manufacturing'},
  {value: '332913', name: 'Plumbing Fixture Fitting and Trim Manufacturing'},
  {value: '332919', name: 'Other Metal Valve and Pipe Fitting Manufacturing'},
  {value: '332991', name: 'Ball and Roller Bearing Manufacturing'},
  {value: '332992', name: 'Small Arms Ammunition Manufacturing'},
  {value: '332993', name: 'Ammunition (except Small Arms) Manufacturing'},
  {value: '332994', name: 'Small Arms, Ordnance, and Ordnance Accessories Manufacturing '},
  {value: '332996', name: 'Fabricated Pipe and Pipe Fitting Manufacturing'},
  {value: '332999', name: 'All Other Miscellaneous Fabricated Metal Product Manufacturing'},
  {value: '333111', name: 'Farm Machinery and Equipment Manufacturing'},
  {value: '333112', name: 'Lawn and Garden Tractor and Home Lawn and Garden Equipment Manufacturing'},
  {value: '333120', name: 'Construction Machinery Manufacturing'},
  {value: '333131', name: 'Mining Machinery and Equipment Manufacturing'},
  {value: '333132', name: 'Oil and Gas Field Machinery and Equipment Manufacturing'},
  {value: '333241', name: 'Food Product Machinery Manufacturing'},
  {value: '333242', name: 'Semiconductor Machinery Manufacturing'},
  {value: '333243', name: 'Sawmill, Woodworking, and Paper Machinery Manufacturing '},
  {value: '333244', name: 'Printing Machinery and Equipment Manufacturing'},
  {value: '333249', name: 'Other Industrial Machinery Manufacturing'},
  {value: '333314', name: 'Optical Instrument and Lens Manufacturing'},
  {value: '333316', name: 'Photographic and Photocopying Equipment Manufacturing'},
  {value: '333318', name: 'Other Commercial and Service Industry Machinery Manufacturing'},
  {value: '333413', name: 'Industrial and Commercial Fan and Blower and Air Purification Equipment Manufacturing'},
  {value: '333414', name: 'Heating Equipment (except Warm Air Furnaces) Manufacturing'},
  {value: '333415', name: 'Air-Conditioning and Warm Air Heating Equipment and Commercial and Industrial Refrigeration Equipment Manufacturing'},
  {value: '333511', name: 'Industrial Mold Manufacturing'},
  {value: '333514', name: 'Special Die and Tool, Die Set, Jig, and Fixture Manufacturing '},
  {value: '333515', name: 'Cutting Tool and Machine Tool Accessory Manufacturing'},
  {value: '333517', name: 'Machine Tool Manufacturing'},
  {value: '333519', name: 'Rolling Mill and Other Metalworking Machinery Manufacturing'},
  {value: '333611', name: 'Turbine and Turbine Generator Set Units Manufacturing'},
  {value: '333612', name: 'Speed Changer, Industrial High-Speed Drive, and Gear Manufacturing '},
  {value: '333613', name: 'Mechanical Power Transmission Equipment Manufacturing'},
  {value: '333618', name: 'Other Engine Equipment Manufacturing'},
  {value: '333912', name: 'Air and Gas Compressor Manufacturing'},
  {value: '333914', name: 'Measuring, Dispensing, and Other Pumping Equipment Manufacturing '},
  {value: '333921', name: 'Elevator and Moving Stairway Manufacturing'},
  {value: '333922', name: 'Conveyor and Conveying Equipment Manufacturing'},
  {value: '333923', name: 'Overhead Traveling Crane, Hoist, and Monorail System Manufacturing '},
  {value: '333924', name: 'Industrial Truck, Tractor, Trailer, and Stacker Machinery Manufacturing '},
  {value: '333991', name: 'Power-Driven Handtool Manufacturing'},
  {value: '333992', name: 'Welding and Soldering Equipment Manufacturing'},
  {value: '333993', name: 'Packaging Machinery Manufacturing'},
  {value: '333994', name: 'Industrial Process Furnace and Oven Manufacturing'},
  {value: '333995', name: 'Fluid Power Cylinder and Actuator Manufacturing'},
  {value: '333996', name: 'Fluid Power Pump and Motor Manufacturing'},
  {value: '333997', name: 'Scale and Balance Manufacturing'},
  {value: '333999', name: 'All Other Miscellaneous General Purpose Machinery Manufacturing'},
  {value: '334111', name: 'Electronic Computer Manufacturing'},
  {value: '334112', name: 'Computer Storage Device Manufacturing'},
  {value: '334118', name: 'Computer Terminal and Other Computer Peripheral Equipment Manufacturing'},
  {value: '334210', name: 'Telephone Apparatus Manufacturing'},
  {value: '334220', name: 'Radio and Television Broadcasting and Wireless Communications Equipment Manufacturing'},
  {value: '334290', name: 'Other Communications Equipment Manufacturing'},
  {value: '334310', name: 'Audio and Video Equipment Manufacturing'},
  {value: '334412', name: 'Bare Printed Circuit Board Manufacturing'},
  {value: '334413', name: 'Semiconductor and Related Device Manufacturing'},
  {value: '334416', name: 'Capacitor, Resistor, Coil, Transformer, and Other Inductor Manufacturing '},
  {value: '334417', name: 'Electronic Connector Manufacturing'},
  {value: '334418', name: 'Printed Circuit Assembly (Electronic Assembly) Manufacturing'},
  {value: '334419', name: 'Other Electronic Component Manufacturing'},
  {value: '334510', name: 'Electromedical and Electrotherapeutic Apparatus Manufacturing'},
  {value: '334511', name: 'Search, Detection, Navigation, Guidance, Aeronautical, and Nautical System and Instrument Manufacturing '},
  {value: '334512', name: 'Automatic Environmental Control Manufacturing for Residential, Commercial, and Appliance Use '},
  {value: '334513', name: 'Instruments and Related Products Manufacturing for Measuring, Displaying, and Controlling Industrial Process Variables '},
  {value: '334514', name: 'Totalizing Fluid Meter and Counting Device Manufacturing'},
  {value: '334515', name: 'Instrument Manufacturing for Measuring and Testing Electricity and Electrical Signals'},
  {value: '334516', name: 'Analytical Laboratory Instrument Manufacturing'},
  {value: '334517', name: 'Irradiation Apparatus Manufacturing'},
  {value: '334519', name: 'Other Measuring and Controlling Device Manufacturing'},
  {value: '334613', name: 'Blank Magnetic and Optical Recording Media Manufacturing'},
  {value: '334614', name: 'Software and Other Prerecorded Compact Disc, Tape, and Record Reproducing '},
  {value: '335110', name: 'Electric Lamp Bulb and Part Manufacturing'},
  {value: '335121', name: 'Residential Electric Lighting Fixture Manufacturing'},
  {value: '335122', name: 'Commercial, Industrial, and Institutional Electric Lighting Fixture Manufacturing '},
  {value: '335129', name: 'Other Lighting Equipment Manufacturing'},
  {value: '335210', name: 'Small Electrical Appliance Manufacturing'},
  {value: '335220', name: 'Major Household Appliance Manufacturing'},
  {value: '335311', name: 'Power, Distribution, and Specialty Transformer Manufacturing '},
  {value: '335312', name: 'Motor and Generator Manufacturing'},
  {value: '335313', name: 'Switchgear and Switchboard Apparatus Manufacturing'},
  {value: '335314', name: 'Relay and Industrial Control Manufacturing'},
  {value: '335911', name: 'Storage Battery Manufacturing'},
  {value: '335912', name: 'Primary Battery Manufacturing'},
  {value: '335921', name: 'Fiber Optic Cable Manufacturing'},
  {value: '335929', name: 'Other Communication and Energy Wire Manufacturing'},
  {value: '335931', name: 'Current-Carrying Wiring Device Manufacturing'},
  {value: '335932', name: 'Noncurrent-Carrying Wiring Device Manufacturing'},
  {value: '335991', name: 'Carbon and Graphite Product Manufacturing'},
  {value: '335999', name: 'All Other Miscellaneous Electrical Equipment and Component Manufacturing'},
  {value: '336111', name: 'Automobile Manufacturing'},
  {value: '336112', name: 'Light Truck and Utility Vehicle Manufacturing'},
  {value: '336120', name: 'Heavy Duty Truck Manufacturing'},
  {value: '336211', name: 'Motor Vehicle Body Manufacturing'},
  {value: '336212', name: 'Truck Trailer Manufacturing'},
  {value: '336213', name: 'Motor Home Manufacturing'},
  {value: '336214', name: 'Travel Trailer and Camper Manufacturing'},
  {value: '336310', name: 'Motor Vehicle Gasoline Engine and Engine Parts Manufacturing'},
  {value: '336320', name: 'Motor Vehicle Electrical and Electronic Equipment Manufacturing'},
  {value: '336330', name: 'Motor Vehicle Steering and Suspension Components (except Spring) Manufacturing'},
  {value: '336340', name: 'Motor Vehicle Brake System Manufacturing'},
  {value: '336350', name: 'Motor Vehicle Transmission and Power Train Parts Manufacturing'},
  {value: '336360', name: 'Motor Vehicle Seating and Interior Trim Manufacturing'},
  {value: '336370', name: 'Motor Vehicle Metal Stamping'},
  {value: '336390', name: 'Other Motor Vehicle Parts Manufacturing'},
  {value: '336411', name: 'Aircraft Manufacturing'},
  {value: '336412', name: 'Aircraft Engine and Engine Parts Manufacturing'},
  {value: '336413', name: 'Other Aircraft Parts and Auxiliary Equipment Manufacturing'},
  {value: '336414', name: 'Guided Missile and Space Vehicle Manufacturing'},
  {value: '336415', name: 'Guided Missile and Space Vehicle Propulsion Unit and Propulsion Unit Parts Manufacturing'},
  {value: '336419', name: 'Other Guided Missile and Space Vehicle Parts and Auxiliary Equipment Manufacturing'},
  {value: '336510', name: 'Railroad Rolling Stock Manufacturing'},
  {value: '336611', name: 'Ship Building and Repairing'},
  {value: '336612', name: 'Boat Building'},
  {value: '336991', name: 'Motorcycle, Bicycle, and Parts Manufacturing '},
  {value: '336992', name: 'Military Armored Vehicle, Tank, and Tank Component Manufacturing '},
  {value: '336999', name: 'All Other Transportation Equipment Manufacturing'},
  {value: '337110', name: 'Wood Kitchen Cabinet and Countertop Manufacturing'},
  {value: '337121', name: 'Upholstered Household Furniture Manufacturing'},
  {value: '337122', name: 'Nonupholstered Wood Household Furniture Manufacturing'},
  {value: '337124', name: 'Metal Household Furniture Manufacturing'},
  {value: '337125', name: 'Household Furniture (except Wood and Metal) Manufacturing'},
  {value: '337127', name: 'Institutional Furniture Manufacturing'},
  {value: '337211', name: 'Wood Office Furniture Manufacturing'},
  {value: '337212', name: 'Custom Architectural Woodwork and Millwork Manufacturing'},
  {value: '337214', name: 'Office Furniture (except Wood) Manufacturing'},
  {value: '337215', name: 'Showcase, Partition, Shelving, and Locker Manufacturing '},
  {value: '337910', name: 'Mattress Manufacturing'},
  {value: '337920', name: 'Blind and Shade Manufacturing'},
  {value: '339112', name: 'Surgical and Medical Instrument Manufacturing'},
  {value: '339113', name: 'Surgical Appliance and Supplies Manufacturing'},
  {value: '339114', name: 'Dental Equipment and Supplies Manufacturing'},
  {value: '339115', name: 'Ophthalmic Goods Manufacturing'},
  {value: '339116', name: 'Dental Laboratories'},
  {value: '339910', name: 'Jewelry and Silverware Manufacturing'},
  {value: '339920', name: 'Sporting and Athletic Goods Manufacturing'},
  {value: '339930', name: 'Doll, Toy, and Game Manufacturing'},
  {value: '339940', name: 'Office Supplies (except Paper) Manufacturing'},
  {value: '339950', name: 'Sign Manufacturing'},
  {value: '339991', name: 'Gasket, Packing, and Sealing Device Manufacturing '},
  {value: '339992', name: 'Musical Instrument Manufacturing'},
  {value: '339993', name: 'Fastener, Button, Needle, and Pin Manufacturing '},
  {value: '339994', name: 'Broom, Brush, and Mop Manufacturing '},
  {value: '339995', name: 'Burial Casket Manufacturing'},
  {value: '339999', name: 'All Other Miscellaneous Manufacturing'},
  {value: '423110', name: 'Automobile and Other Motor Vehicle Merchant Wholesalers'},
  {value: '423120', name: 'Motor Vehicle Supplies and New Parts Merchant Wholesalers'},
  {value: '423130', name: 'Tire and Tube Merchant Wholesalers'},
  {value: '423140', name: 'Motor Vehicle Parts (Used) Merchant Wholesalers'},
  {value: '423210', name: 'Furniture Merchant Wholesalers'},
  {value: '423220', name: 'Home Furnishing Merchant Wholesalers'},
  {value: '423310', name: 'Lumber, Plywood, Millwork, and Wood Panel Merchant Wholesalers '},
  {value: '423320', name: 'Brick, Stone, and Related Construction Material Merchant Wholesalers '},
  {value: '423330', name: 'Roofing, Siding, and Insulation Material Merchant Wholesalers '},
  {value: '423390', name: 'Other Construction Material Merchant Wholesalers'},
  {value: '423410', name: 'Photographic Equipment and Supplies Merchant Wholesalers'},
  {value: '423420', name: 'Office Equipment Merchant Wholesalers'},
  {value: '423430', name: 'Computer and Computer Peripheral Equipment and Software Merchant Wholesalers'},
  {value: '423440', name: 'Other Commercial Equipment Merchant Wholesalers'},
  {value: '423450', name: 'Medical, Dental, and Hospital Equipment and Supplies Merchant Wholesalers '},
  {value: '423460', name: 'Ophthalmic Goods Merchant Wholesalers'},
  {value: '423490', name: 'Other Professional Equipment and Supplies Merchant Wholesalers'},
  {value: '423510', name: 'Metal Service Centers and Other Metal Merchant Wholesalers'},
  {value: '423520', name: 'Coal and Other Mineral and Ore Merchant Wholesalers'},
  {value: '423610', name: 'Electrical Apparatus and Equipment, Wiring Supplies, and Related Equipment Merchant Wholesalers '},
  {value: '423620', name: 'Household Appliances, Electric Housewares, and Consumer Electronics Merchant Wholesalers '},
  {value: '423690', name: 'Other Electronic Parts and Equipment Merchant Wholesalers'},
  {value: '423710', name: 'Hardware Merchant Wholesalers'},
  {value: '423720', name: 'Plumbing and Heating Equipment and Supplies (Hydronics) Merchant Wholesalers'},
  {value: '423730', name: 'Warm Air Heating and Air-Conditioning Equipment and Supplies Merchant Wholesalers'},
  {value: '423740', name: 'Refrigeration Equipment and Supplies Merchant Wholesalers'},
  {value: '423810', name: 'Construction and Mining (except Oil Well) Machinery and Equipment Merchant Wholesalers'},
  {value: '423820', name: 'Farm and Garden Machinery and Equipment Merchant Wholesalers'},
  {value: '423830', name: 'Industrial Machinery and Equipment Merchant Wholesalers'},
  {value: '423840', name: 'Industrial Supplies Merchant Wholesalers'},
  {value: '423850', name: 'Service Establishment Equipment and Supplies Merchant Wholesalers'},
  {value: '423860', name: 'Transportation Equipment and Supplies (except Motor Vehicle) Merchant Wholesalers'},
  {value: '423910', name: 'Sporting and Recreational Goods and Supplies Merchant Wholesalers'},
  {value: '423920', name: 'Toy and Hobby Goods and Supplies Merchant Wholesalers'},
  {value: '423930', name: 'Recyclable Material Merchant Wholesalers'},
  {value: '423940', name: 'Jewelry, Watch, Precious Stone, and Precious Metal Merchant Wholesalers '},
  {value: '423990', name: 'Other Miscellaneous Durable Goods Merchant Wholesalers'},
  {value: '424110', name: 'Printing and Writing Paper Merchant Wholesalers'},
  {value: '424120', name: 'Stationery and Office Supplies Merchant Wholesalers'},
  {value: '424130', name: 'Industrial and Personal Service Paper Merchant Wholesalers'},
  {value: '424210', name: 'Drugs and Druggists Sundries Merchant Wholesalers'},
  {value: '424310', name: 'Piece Goods, Notions, and Other Dry Goods Merchant Wholesalers '},
  {value: '424320', name: 'Men\'s and Boys\' Clothing and Furnishings Merchant Wholesalers'},
  {value: '424330', name: 'Women\'s, Children\'s, and Infants\' Clothing and Accessories Merchant Wholesalers'},
  {value: '424340', name: 'Footwear Merchant Wholesalers'},
  {value: '424410', name: 'General Line Grocery Merchant Wholesalers'},
  {value: '424420', name: 'Packaged Frozen Food Merchant Wholesalers'},
  {value: '424430', name: 'Dairy Product (except Dried or Canned) Merchant Wholesalers'},
  {value: '424440', name: 'Poultry and Poultry Product Merchant Wholesalers'},
  {value: '424450', name: 'Confectionery Merchant Wholesalers'},
  {value: '424460', name: 'Fish and Seafood Merchant Wholesalers'},
  {value: '424470', name: 'Meat and Meat Product Merchant Wholesalers'},
  {value: '424480', name: 'Fresh Fruit and Vegetable Merchant Wholesalers'},
  {value: '424490', name: 'Other Grocery and Related Products Merchant Wholesalers'},
  {value: '424510', name: 'Grain and Field Bean Merchant Wholesalers'},
  {value: '424520', name: 'Livestock Merchant Wholesalers'},
  {value: '424590', name: 'Other Farm Product Raw Material Merchant Wholesalers'},
  {value: '424610', name: 'Plastics Materials and Basic Forms and Shapes Merchant Wholesalers'},
  {value: '424690', name: 'Other Chemical and Allied Products Merchant Wholesalers'},
  {value: '424710', name: 'Petroleum Bulk Stations and Terminals'},
  {value: '424720', name: 'Petroleum and Petroleum Products Merchant Wholesalers (except Bulk Stations and Terminals)'},
  {value: '424810', name: 'Beer and Ale Merchant Wholesalers'},
  {value: '424820', name: 'Wine and Distilled Alcoholic Beverage Merchant Wholesalers'},
  {value: '424910', name: 'Farm Supplies Merchant Wholesalers'},
  {value: '424920', name: 'Book, Periodical, and Newspaper Merchant Wholesalers '},
  {value: '424930', name: 'Flower, Nursery Stock, and Florists\' Supplies Merchant Wholesalers '},
  {value: '424940', name: 'Tobacco and Tobacco Product Merchant Wholesalers'},
  {value: '424950', name: 'Paint, Varnish, and Supplies Merchant Wholesalers '},
  {value: '424990', name: 'Other Miscellaneous Nondurable Goods Merchant Wholesalers'},
  {value: '425110', name: 'Business to Business Electronic Markets'},
  {value: '425120', name: 'Wholesale Trade Agents and Brokers'},
  {value: '441110', name: 'New Car Dealers'},
  {value: '441120', name: 'Used Car Dealers'},
  {value: '441210', name: 'Recreational Vehicle Dealers'},
  {value: '441222', name: 'Boat Dealers'},
  {value: '441228', name: 'Motorcycle, ATV, and All Other Motor Vehicle Dealers '},
  {value: '441310', name: 'Automotive Parts and Accessories Stores'},
  {value: '441320', name: 'Tire Dealers'},
  {value: '442110', name: 'Furniture Stores'},
  {value: '442210', name: 'Floor Covering Stores'},
  {value: '442291', name: 'Window Treatment Stores'},
  {value: '442299', name: 'All Other Home Furnishings Stores'},
  {value: '443141', name: 'Household Appliance Stores'},
  {value: '443142', name: 'Electronics Stores'},
  {value: '444110', name: 'Home Centers'},
  {value: '444120', name: 'Paint and Wallpaper Stores'},
  {value: '444130', name: 'Hardware Stores'},
  {value: '444190', name: 'Other Building Material Dealers'},
  {value: '444210', name: 'Outdoor Power Equipment Stores'},
  {value: '444220', name: 'Nursery, Garden Center, and Farm Supply Stores '},
  {value: '445110', name: 'Supermarkets and Other Grocery (except Convenience) Stores'},
  {value: '445120', name: 'Convenience Stores'},
  {value: '445210', name: 'Meat Markets'},
  {value: '445220', name: 'Fish and Seafood Markets'},
  {value: '445230', name: 'Fruit and Vegetable Markets'},
  {value: '445291', name: 'Baked Goods Stores'},
  {value: '445292', name: 'Confectionery and Nut Stores'},
  {value: '445299', name: 'All Other Specialty Food Stores'},
  {value: '445310', name: 'Beer, Wine, and Liquor Stores '},
  {value: '446110', name: 'Pharmacies and Drug Stores'},
  {value: '446120', name: 'Cosmetics, Beauty Supplies, and Perfume Stores '},
  {value: '446130', name: 'Optical Goods Stores'},
  {value: '446191', name: 'Food (Health) Supplement Stores'},
  {value: '446199', name: 'All Other Health and Personal Care Stores'},
  {value: '447110', name: 'Gasoline Stations with Convenience Stores'},
  {value: '447190', name: 'Other Gasoline Stations'},
  {value: '448110', name: 'Men\'s Clothing Stores'},
  {value: '448120', name: 'Women\'s Clothing Stores'},
  {value: '448130', name: 'Children\'s and Infants\' Clothing Stores'},
  {value: '448140', name: 'Family Clothing Stores'},
  {value: '448150', name: 'Clothing Accessories Stores'},
  {value: '448190', name: 'Other Clothing Stores'},
  {value: '448210', name: 'Shoe Stores'},
  {value: '448310', name: 'Jewelry Stores'},
  {value: '448320', name: 'Luggage and Leather Goods Stores'},
  {value: '451110', name: 'Sporting Goods Stores'},
  {value: '451120', name: 'Hobby, Toy, and Game Stores '},
  {value: '451130', name: 'Sewing, Needlework, and Piece Goods Stores '},
  {value: '451140', name: 'Musical Instrument and Supplies Stores'},
  {value: '451211', name: 'Book Stores'},
  {value: '451212', name: 'News Dealers and Newsstands'},
  {value: '452210', name: 'Department Stores'},
  {value: '452311', name: 'Warehouse Clubs and Supercenters'},
  {value: '452319', name: 'All Other General Merchandise Stores'},
  {value: '453110', name: 'Florists'},
  {value: '453210', name: 'Office Supplies and Stationery Stores'},
  {value: '453220', name: 'Gift, Novelty, and Souvenir Stores '},
  {value: '453310', name: 'Used Merchandise Stores'},
  {value: '453910', name: 'Pet and Pet Supplies Stores'},
  {value: '453920', name: 'Art Dealers'},
  {value: '453930', name: 'Manufactured (Mobile) Home Dealers'},
  {value: '453991', name: 'Tobacco Stores'},
  {value: '453998', name: 'All Other Miscellaneous Store Retailers (except Tobacco Stores)'},
  {value: '454110', name: 'Electronic Shopping and Mail-Order Houses'},
  {value: '454210', name: 'Vending Machine Operators'},
  {value: '454310', name: 'Fuel Dealers'},
  {value: '454390', name: 'Other Direct Selling Establishments'},
  {value: '481111', name: 'Scheduled Passenger Air Transportation'},
  {value: '481112', name: 'Scheduled Freight Air Transportation'},
  {value: '481211', name: 'Nonscheduled Chartered Passenger Air Transportation'},
  {value: '481212', name: 'Nonscheduled Chartered Freight Air Transportation'},
  {value: '481219', name: 'Other Nonscheduled Air Transportation'},
  {value: '482111', name: 'Line-Haul Railroads'},
  {value: '482112', name: 'Short Line Railroads'},
  {value: '483111', name: 'Deep Sea Freight Transportation'},
  {value: '483112', name: 'Deep Sea Passenger Transportation'},
  {value: '483113', name: 'Coastal and Great Lakes Freight Transportation'},
  {value: '483114', name: 'Coastal and Great Lakes Passenger Transportation'},
  {value: '483211', name: 'Inland Water Freight Transportation'},
  {value: '483212', name: 'Inland Water Passenger Transportation'},
  {value: '484110', name: 'General Freight Trucking, Local '},
  {value: '484121', name: 'General Freight Trucking, Long-Distance, Truckload '},
  {value: '484122', name: 'General Freight Trucking, Long-Distance, Less Than Truckload '},
  {value: '484210', name: 'Used Household and Office Goods Moving'},
  {value: '484220', name: 'Specialized Freight (except Used Goods) Trucking, Local '},
  {value: '484230', name: 'Specialized Freight (except Used Goods) Trucking, Long-Distance '},
  {value: '485111', name: 'Mixed Mode Transit Systems'},
  {value: '485112', name: 'Commuter Rail Systems'},
  {value: '485113', name: 'Bus and Other Motor Vehicle Transit Systems'},
  {value: '485119', name: 'Other Urban Transit Systems'},
  {value: '485210', name: 'Interurban and Rural Bus Transportation'},
  {value: '485310', name: 'Taxi Service'},
  {value: '485320', name: 'Limousine Service'},
  {value: '485410', name: 'School and Employee Bus Transportation'},
  {value: '485510', name: 'Charter Bus Industry'},
  {value: '485991', name: 'Special Needs Transportation'},
  {value: '485999', name: 'All Other Transit and Ground Passenger Transportation'},
  {value: '486110', name: 'Pipeline Transportation of Crude Oil'},
  {value: '486210', name: 'Pipeline Transportation of Natural Gas'},
  {value: '486910', name: 'Pipeline Transportation of Refined Petroleum Products'},
  {value: '486990', name: 'All Other Pipeline Transportation'},
  {value: '487110', name: 'Scenic and Sightseeing Transportation, Land'},
  {value: '487210', name: 'Scenic and Sightseeing Transportation, Water'},
  {value: '487990', name: 'Scenic and Sightseeing Transportation, Other'},
  {value: '488111', name: 'Air Traffic Control'},
  {value: '488119', name: 'Other Airport Operations'},
  {value: '488190', name: 'Other Support Activities for Air Transportation'},
  {value: '488210', name: 'Support Activities for Rail Transportation'},
  {value: '488310', name: 'Port and Harbor Operations'},
  {value: '488320', name: 'Marine Cargo Handling'},
  {value: '488330', name: 'Navigational Services to Shipping'},
  {value: '488390', name: 'Other Support Activities for Water Transportation'},
  {value: '488410', name: 'Motor Vehicle Towing'},
  {value: '488490', name: 'Other Support Activities for Road Transportation'},
  {value: '488510', name: 'Freight Transportation Arrangement'},
  {value: '488991', name: 'Packing and Crating'},
  {value: '488999', name: 'All Other Support Activities for Transportation'},
  {value: '491110', name: 'Postal Service'},
  {value: '492110', name: 'Couriers and Express Delivery Services'},
  {value: '492210', name: 'Local Messengers and Local Delivery'},
  {value: '493110', name: 'General Warehousing and Storage'},
  {value: '493120', name: 'Refrigerated Warehousing and Storage'},
  {value: '493130', name: 'Farm Product Warehousing and Storage'},
  {value: '493190', name: 'Other Warehousing and Storage'},
  {value: '511110', name: 'Newspaper Publishers'},
  {value: '511120', name: 'Periodical Publishers'},
  {value: '511130', name: 'Book Publishers'},
  {value: '511140', name: 'Directory and Mailing List Publishers'},
  {value: '511191', name: 'Greeting Card Publishers'},
  {value: '511199', name: 'All Other Publishers'},
  {value: '511210', name: 'Software Publishers'},
  {value: '512110', name: 'Motion Picture and Video Production'},
  {value: '512120', name: 'Motion Picture and Video Distribution'},
  {value: '512131', name: 'Motion Picture Theaters (except Drive-Ins)'},
  {value: '512132', name: 'Drive-In Motion Picture Theaters'},
  {value: '512191', name: 'Teleproduction and Other Postproduction Services'},
  {value: '512199', name: 'Other Motion Picture and Video Industries'},
  {value: '512230', name: 'Music Publishers'},
  {value: '512240', name: 'Sound Recording Studios'},
  {value: '512250', name: 'Record Production and Distribution'},
  {value: '512290', name: 'Other Sound Recording Industries'},
  {value: '515111', name: 'Radio Networks'},
  {value: '515112', name: 'Radio Stations'},
  {value: '515120', name: 'Television Broadcasting'},
  {value: '515210', name: 'Cable and Other Subscription Programming'},
  {value: '517311', name: 'Wired Telecommunications Carriers'},
  {value: '517312', name: 'Wireless Telecommunications Carriers (except Satellite)'},
  {value: '517410', name: 'Satellite Telecommunications'},
  {value: '517911', name: 'Telecommunications Resellers'},
  {value: '517919', name: 'All Other Telecommunications'},
  {value: '518210', name: 'Data Processing, Hosting, and Related Services'},
  {value: '519110', name: 'News Syndicates'},
  {value: '519120', name: 'Libraries and Archives'},
  {value: '519130', name: 'Internet Publishing and Broadcasting and Web Search Portals'},
  {value: '519190', name: 'All Other Information Services'},
  {value: '521110', name: 'Monetary Authorities-Central Bank'},
  {value: '522110', name: 'Commercial Banking'},
  {value: '522120', name: 'Savings Institutions'},
  {value: '522130', name: 'Credit Unions'},
  {value: '522190', name: 'Other Depository Credit Intermediation'},
  {value: '522210', name: 'Credit Card Issuing'},
  {value: '522220', name: 'Sales Financing'},
  {value: '522291', name: 'Consumer Lending'},
  {value: '522292', name: 'Real Estate Credit'},
  {value: '522293', name: 'International Trade Financing'},
  {value: '522294', name: 'Secondary Market Financing'},
  {value: '522298', name: 'All Other Nondepository Credit Intermediation'},
  {value: '522310', name: 'Mortgage and Nonmortgage Loan Brokers'},
  {value: '522320', name: 'Financial Transactions Processing, Reserve, and Clearinghouse Activities '},
  {value: '522390', name: 'Other Activities Related to Credit Intermediation'},
  {value: '523110', name: 'Investment Banking and Securities Dealing'},
  {value: '523120', name: 'Securities Brokerage'},
  {value: '523130', name: 'Commodity Contracts Dealing'},
  {value: '523140', name: 'Commodity Contracts Brokerage'},
  {value: '523210', name: 'Securities and Commodity Exchanges'},
  {value: '523910', name: 'Miscellaneous Intermediation'},
  {value: '523920', name: 'Portfolio Management'},
  {value: '523930', name: 'Investment Advice'},
  {value: '523991', name: 'Trust, Fiduciary, and Custody Activities '},
  {value: '523999', name: 'Miscellaneous Financial Investment Activities'},
  {value: '524113', name: 'Direct Life Insurance Carriers'},
  {value: '524114', name: 'Direct Health and Medical Insurance Carriers'},
  {value: '524126', name: 'Direct Property and Casualty Insurance Carriers'},
  {value: '524127', name: 'Direct Title Insurance Carriers'},
  {value: '524128', name: 'Other Direct Insurance (except Life, Health, and Medical) Carriers '},
  {value: '524130', name: 'Reinsurance Carriers'},
  {value: '524210', name: 'Insurance Agencies and Brokerages'},
  {value: '524291', name: 'Claims Adjusting'},
  {value: '524292', name: 'Third Party Administration of Insurance and Pension Funds'},
  {value: '524298', name: 'All Other Insurance Related Activities'},
  {value: '525110', name: 'Pension Funds'},
  {value: '525120', name: 'Health and Welfare Funds'},
  {value: '525190', name: 'Other Insurance Funds'},
  {value: '525910', name: 'Open-End Investment Funds'},
  {value: '525920', name: 'Trusts, Estates, and Agency Accounts'},
  {value: '525990', name: 'Other Financial Vehicles'},
  {value: '531110', name: 'Lessors of Residential Buildings and Dwellings'},
  {value: '531120', name: 'Lessors of Nonresidential Buildings (except Miniwarehouses)'},
  {value: '531130', name: 'Lessors of Miniwarehouses and Self-Storage Units'},
  {value: '531190', name: 'Lessors of Other Real Estate Property'},
  {value: '531210', name: 'Offices of Real Estate Agents and Brokers'},
  {value: '531311', name: 'Residential Property Managers'},
  {value: '531312', name: 'Nonresidential Property Managers'},
  {value: '531320', name: 'Offices of Real Estate Appraisers'},
  {value: '531390', name: 'Other Activities Related to Real Estate'},
  {value: '532111', name: 'Passenger Car Rental'},
  {value: '532112', name: 'Passenger Car Leasing'},
  {value: '532120', name: 'Truck, Utility Trailer, and RV (Recreational Vehicle) Rental and Leasing '},
  {value: '532210', name: 'Consumer Electronics and Appliances Rental'},
  {value: '532281', name: 'Formal Wear and Costume Rental'},
  {value: '532282', name: 'Video Tape and Disc Rental'},
  {value: '532283', name: 'Home Health Equipment Rental'},
  {value: '532284', name: 'Recreational Goods Rental'},
  {value: '532289', name: 'All Other Consumer Goods Rental'},
  {value: '532310', name: 'General Rental Centers'},
  {value: '532411', name: 'Commercial Air, Rail, and Water Transportation Equipment Rental and Leasing '},
  {value: '532412', name: 'Construction, Mining, and Forestry Machinery and Equipment Rental and Leasing '},
  {value: '532420', name: 'Office Machinery and Equipment Rental and Leasing'},
  {value: '532490', name: 'Other Commercial and Industrial Machinery and Equipment Rental and Leasing'},
  {value: '533110', name: 'Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)'},
  {value: '541110', name: 'Offices of Lawyers'},
  {value: '541120', name: 'Offices of Notaries'},
  {value: '541191', name: 'Title Abstract and Settlement Offices'},
  {value: '541199', name: 'All Other Legal Services'},
  {value: '541211', name: 'Offices of Certified Public Accountants'},
  {value: '541213', name: 'Tax Preparation Services'},
  {value: '541214', name: 'Payroll Services'},
  {value: '541219', name: 'Other Accounting Services'},
  {value: '541310', name: 'Architectural Services'},
  {value: '541320', name: 'Landscape Architectural Services'},
  {value: '541330', name: 'Engineering Services'},
  {value: '541340', name: 'Drafting Services'},
  {value: '541350', name: 'Building Inspection Services'},
  {value: '541360', name: 'Geophysical Surveying and Mapping Services'},
  {value: '541370', name: 'Surveying and Mapping (except Geophysical) Services'},
  {value: '541380', name: 'Testing Laboratories'},
  {value: '541410', name: 'Interior Design Services'},
  {value: '541420', name: 'Industrial Design Services'},
  {value: '541430', name: 'Graphic Design Services'},
  {value: '541490', name: 'Other Specialized Design Services'},
  {value: '541511', name: 'Custom Computer Programming Services'},
  {value: '541512', name: 'Computer Systems Design Services'},
  {value: '541513', name: 'Computer Facilities Management Services'},
  {value: '541519', name: 'Other Computer Related Services'},
  {value: '541611', name: 'Administrative Management and General Management Consulting Services'},
  {value: '541612', name: 'Human Resources Consulting Services'},
  {value: '541613', name: 'Marketing Consulting Services'},
  {value: '541614', name: 'Process, Physical Distribution, and Logistics Consulting Services '},
  {value: '541618', name: 'Other Management Consulting Services'},
  {value: '541620', name: 'Environmental Consulting Services'},
  {value: '541690', name: 'Other Scientific and Technical Consulting Services'},
  {value: '541713', name: 'Research and Development in Nanotechnology'},
  {value: '541714', name: 'Research and Development in Biotechnology (except Nanobiotechnology)'},
  {value: '541715', name: 'Research and Development in the Physical, Engineering, and Life Sciences (except Nanotechnology and Biotechnology) '},
  {value: '541720', name: 'Research and Development in the Social Sciences and Humanities'},
  {value: '541810', name: 'Advertising Agencies'},
  {value: '541820', name: 'Public Relations Agencies'},
  {value: '541830', name: 'Media Buying Agencies'},
  {value: '541840', name: 'Media Representatives'},
  {value: '541850', name: 'Outdoor Advertising'},
  {value: '541860', name: 'Direct Mail Advertising'},
  {value: '541870', name: 'Advertising Material Distribution Services'},
  {value: '541890', name: 'Other Services Related to Advertising'},
  {value: '541910', name: 'Marketing Research and Public Opinion Polling'},
  {value: '541921', name: 'Photography Studios, Portrait '},
  {value: '541922', name: 'Commercial Photography'},
  {value: '541930', name: 'Translation and Interpretation Services'},
  {value: '541940', name: 'Veterinary Services'},
  {value: '541990', name: 'All Other Professional, Scientific, and Technical Services'},
  {value: '551111', name: 'Offices of Bank Holding Companies'},
  {value: '551112', name: 'Offices of Other Holding Companies'},
  {value: '551114', name: 'Corporate, Subsidiary, and Regional Managing Offices '},
  {value: '561110', name: 'Office Administrative Services'},
  {value: '561210', name: 'Facilities Support Services'},
  {value: '561311', name: 'Employment Placement Agencies'},
  {value: '561312', name: 'Executive Search Services'},
  {value: '561320', name: 'Temporary Help Services'},
  {value: '561330', name: 'Professional Employer Organizations'},
  {value: '561410', name: 'Document Preparation Services'},
  {value: '561421', name: 'Telephone Answering Services'},
  {value: '561422', name: 'Telemarketing Bureaus and Other Contact Centers'},
  {value: '561431', name: 'Private Mail Centers'},
  {value: '561439', name: 'Other Business Service Centers (including Copy Shops)'},
  {value: '561440', name: 'Collection Agencies'},
  {value: '561450', name: 'Credit Bureaus'},
  {value: '561491', name: 'Repossession Services'},
  {value: '561492', name: 'Court Reporting and Stenotype Services'},
  {value: '561499', name: 'All Other Business Support Services'},
  {value: '561510', name: 'Travel Agencies'},
  {value: '561520', name: 'Tour Operators'},
  {value: '561591', name: 'Convention and Visitors Bureaus'},
  {value: '561599', name: 'All Other Travel Arrangement and Reservation Services'},
  {value: '561611', name: 'Investigation Services'},
  {value: '561612', name: 'Security Guards and Patrol Services'},
  {value: '561613', name: 'Armored Car Services'},
  {value: '561621', name: 'Security Systems Services (except Locksmiths)'},
  {value: '561622', name: 'Locksmiths'},
  {value: '561710', name: 'Exterminating and Pest Control Services'},
  {value: '561720', name: 'Janitorial Services'},
  {value: '561730', name: 'Landscaping Services'},
  {value: '561740', name: 'Carpet and Upholstery Cleaning Services'},
  {value: '561790', name: 'Other Services to Buildings and Dwellings'},
  {value: '561910', name: 'Packaging and Labeling Services'},
  {value: '561920', name: 'Convention and Trade Show Organizers'},
  {value: '561990', name: 'All Other Support Services'},
  {value: '562111', name: 'Solid Waste Collection'},
  {value: '562112', name: 'Hazardous Waste Collection'},
  {value: '562119', name: 'Other Waste Collection'},
  {value: '562211', name: 'Hazardous Waste Treatment and Disposal'},
  {value: '562212', name: 'Solid Waste Landfill'},
  {value: '562213', name: 'Solid Waste Combustors and Incinerators'},
  {value: '562219', name: 'Other Nonhazardous Waste Treatment and Disposal'},
  {value: '562910', name: 'Remediation Services'},
  {value: '562920', name: 'Materials Recovery Facilities'},
  {value: '562991', name: 'Septic Tank and Related Services'},
  {value: '562998', name: 'All Other Miscellaneous Waste Management Services'},
  {value: '611110', name: 'Elementary and Secondary Schools'},
  {value: '611210', name: 'Junior Colleges'},
  {value: '611310', name: 'Colleges, Universities, and Professional Schools '},
  {value: '611410', name: 'Business and Secretarial Schools'},
  {value: '611420', name: 'Computer Training'},
  {value: '611430', name: 'Professional and Management Development Training'},
  {value: '611511', name: 'Cosmetology and Barber Schools'},
  {value: '611512', name: 'Flight Training'},
  {value: '611513', name: 'Apprenticeship Training'},
  {value: '611519', name: 'Other Technical and Trade Schools'},
  {value: '611610', name: 'Fine Arts Schools'},
  {value: '611620', name: 'Sports and Recreation Instruction'},
  {value: '611630', name: 'Language Schools'},
  {value: '611691', name: 'Exam Preparation and Tutoring'},
  {value: '611692', name: 'Automobile Driving Schools'},
  {value: '611699', name: 'All Other Miscellaneous Schools and Instruction'},
  {value: '611710', name: 'Educational Support Services'},
  {value: '621111', name: 'Offices of Physicians (except Mental Health Specialists)'},
  {value: '621112', name: 'Offices of Physicians, Mental Health Specialists '},
  {value: '621210', name: 'Offices of Dentists'},
  {value: '621310', name: 'Offices of Chiropractors'},
  {value: '621320', name: 'Offices of Optometrists'},
  {value: '621330', name: 'Offices of Mental Health Practitioners (except Physicians)'},
  {value: '621340', name: 'Offices of Physical, Occupational and Speech Therapists, and Audiologists '},
  {value: '621391', name: 'Offices of Podiatrists'},
  {value: '621399', name: 'Offices of All Other Miscellaneous Health Practitioners'},
  {value: '621410', name: 'Family Planning Centers'},
  {value: '621420', name: 'Outpatient Mental Health and Substance Abuse Centers'},
  {value: '621491', name: 'HMO Medical Centers'},
  {value: '621492', name: 'Kidney Dialysis Centers'},
  {value: '621493', name: 'Freestanding Ambulatory Surgical and Emergency Centers'},
  {value: '621498', name: 'All Other Outpatient Care Centers'},
  {value: '621511', name: 'Medical Laboratories'},
  {value: '621512', name: 'Diagnostic Imaging Centers'},
  {value: '621610', name: 'Home Health Care Services'},
  {value: '621910', name: 'Ambulance Services'},
  {value: '621991', name: 'Blood and Organ Banks'},
  {value: '621999', name: 'All Other Miscellaneous Ambulatory Health Care Services'},
  {value: '622110', name: 'General Medical and Surgical Hospitals'},
  {value: '622210', name: 'Psychiatric and Substance Abuse Hospitals'},
  {value: '622310', name: 'Specialty (except Psychiatric and Substance Abuse) Hospitals'},
  {value: '623110', name: 'Nursing Care Facilities (Skilled Nursing Facilities)'},
  {value: '623210', name: 'Residential Intellectual and Developmental Disability Facilities'},
  {value: '623220', name: 'Residential Mental Health and Substance Abuse Facilities'},
  {value: '623311', name: 'Continuing Care Retirement Communities'},
  {value: '623312', name: 'Assisted Living Facilities for the Elderly'},
  {value: '623990', name: 'Other Residential Care Facilities'},
  {value: '624110', name: 'Child and Youth Services'},
  {value: '624120', name: 'Services for the Elderly and Persons with Disabilities'},
  {value: '624190', name: 'Other Individual and Family Services'},
  {value: '624210', name: 'Community Food Services'},
  {value: '624221', name: 'Temporary Shelters'},
  {value: '624229', name: 'Other Community Housing Services'},
  {value: '624230', name: 'Emergency and Other Relief Services'},
  {value: '624310', name: 'Vocational Rehabilitation Services'},
  {value: '624410', name: 'Child Day Care Services'},
  {value: '711110', name: 'Theater Companies and Dinner Theaters'},
  {value: '711120', name: 'Dance Companies'},
  {value: '711130', name: 'Musical Groups and Artists'},
  {value: '711190', name: 'Other Performing Arts Companies'},
  {value: '711211', name: 'Sports Teams and Clubs'},
  {value: '711212', name: 'Racetracks'},
  {value: '711219', name: 'Other Spectator Sports'},
  {value: '711310', name: 'Promoters of Performing Arts, Sports, and Similar Events with Facilities '},
  {value: '711320', name: 'Promoters of Performing Arts, Sports, and Similar Events without Facilities '},
  {value: '711410', name: 'Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures'},
  {value: '711510', name: 'Independent Artists, Writers, and Performers '},
  {value: '712110', name: 'Museums'},
  {value: '712120', name: 'Historical Sites'},
  {value: '712130', name: 'Zoos and Botanical Gardens'},
  {value: '712190', name: 'Nature Parks and Other Similar Institutions'},
  {value: '713110', name: 'Amusement and Theme Parks'},
  {value: '713120', name: 'Amusement Arcades'},
  {value: '713210', name: 'Casinos (except Casino Hotels)'},
  {value: '713290', name: 'Other Gambling Industries'},
  {value: '713910', name: 'Golf Courses and Country Clubs'},
  {value: '713920', name: 'Skiing Facilities'},
  {value: '713930', name: 'Marinas'},
  {value: '713940', name: 'Fitness and Recreational Sports Centers'},
  {value: '713950', name: 'Bowling Centers'},
  {value: '713990', name: 'All Other Amusement and Recreation Industries'},
  {value: '721110', name: 'Hotels (except Casino Hotels) and Motels'},
  {value: '721120', name: 'Casino Hotels'},
  {value: '721191', name: 'Bed-and-Breakfast Inns'},
  {value: '721199', name: 'All Other Traveler Accommodation'},
  {value: '721211', name: 'RV (Recreational Vehicle) Parks and Campgrounds'},
  {value: '721214', name: 'Recreational and Vacation Camps (except Campgrounds)'},
  {value: '721310', name: 'Rooming and Boarding Houses, Dormitories, and Workers Camps '},
  {value: '722310', name: 'Food Service Contractors'},
  {value: '722320', name: 'Caterers'},
  {value: '722330', name: 'Mobile Food Services'},
  {value: '722410', name: 'Drinking Places (Alcoholic Beverages)'},
  {value: '722511', name: 'Full-Service Restaurants'},
  {value: '722513', name: 'Limited-Service Restaurants'},
  {value: '722514', name: 'Cafeterias, Grill Buffets, and Buffets '},
  {value: '722515', name: 'Snack and Nonalcoholic Beverage Bars'},
  {value: '811111', name: 'General Automotive Repair'},
  {value: '811112', name: 'Automotive Exhaust System Repair'},
  {value: '811113', name: 'Automotive Transmission Repair'},
  {value: '811118', name: 'Other Automotive Mechanical and Electrical Repair and Maintenance'},
  {value: '811121', name: 'Automotive Body, Paint, and Interior Repair and Maintenance '},
  {value: '811122', name: 'Automotive Glass Replacement Shops'},
  {value: '811191', name: 'Automotive Oil Change and Lubrication Shops'},
  {value: '811192', name: 'Car Washes'},
  {value: '811198', name: 'All Other Automotive Repair and Maintenance'},
  {value: '811211', name: 'Consumer Electronics Repair and Maintenance'},
  {value: '811212', name: 'Computer and Office Machine Repair and Maintenance'},
  {value: '811213', name: 'Communication Equipment Repair and Maintenance'},
  {value: '811219', name: 'Other Electronic and Precision Equipment Repair and Maintenance'},
  {value: '811310', name: 'Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair and Maintenance'},
  {value: '811411', name: 'Home and Garden Equipment Repair and Maintenance'},
  {value: '811412', name: 'Appliance Repair and Maintenance'},
  {value: '811420', name: 'Reupholstery and Furniture Repair'},
  {value: '811430', name: 'Footwear and Leather Goods Repair'},
  {value: '811490', name: 'Other Personal and Household Goods Repair and Maintenance'},
  {value: '812111', name: 'Barber Shops'},
  {value: '812112', name: 'Beauty Salons'},
  {value: '812113', name: 'Nail Salons'},
  {value: '812191', name: 'Diet and Weight Reducing Centers'},
  {value: '812199', name: 'Other Personal Care Services'},
  {value: '812210', name: 'Funeral Homes and Funeral Services'},
  {value: '812220', name: 'Cemeteries and Crematories'},
  {value: '812310', name: 'Coin-Operated Laundries and Drycleaners'},
  {value: '812320', name: 'Drycleaning and Laundry Services (except Coin-Operated)'},
  {value: '812331', name: 'Linen Supply'},
  {value: '812332', name: 'Industrial Launderers'},
  {value: '812910', name: 'Pet Care (except Veterinary) Services'},
  {value: '812921', name: 'Photofinishing Laboratories (except One-Hour)'},
  {value: '812922', name: 'One-Hour Photofinishing'},
  {value: '812930', name: 'Parking Lots and Garages'},
  {value: '812990', name: 'All Other Personal Services'},
  {value: '813110', name: 'Religious Organizations'},
  {value: '813211', name: 'Grantmaking Foundations'},
  {value: '813212', name: 'Voluntary Health Organizations'},
  {value: '813219', name: 'Other Grantmaking and Giving Services'},
  {value: '813311', name: 'Human Rights Organizations'},
  {value: '813312', name: 'Environment, Conservation and Wildlife Organizations '},
  {value: '813319', name: 'Other Social Advocacy Organizations'},
  {value: '813410', name: 'Civic and Social Organizations'},
  {value: '813910', name: 'Business Associations'},
  {value: '813920', name: 'Professional Organizations'},
  {value: '813930', name: 'Labor Unions and Similar Labor Organizations'},
  {value: '813940', name: 'Political Organizations'},
  {value: '813990', name: 'Other Similar Organizations (except Business, Professional, Labor, and Political Organizations) '},
  {value: '814110', name: 'Private Households'},
  {value: '921110', name: 'Executive Offices'},
  {value: '921120', name: 'Legislative Bodies'},
  {value: '921130', name: 'Public Finance Activities'},
  {value: '921140', name: 'Executive and Legislative Offices, Combined '},
  {value: '921150', name: 'American Indian and Alaska Native Tribal Governments'},
  {value: '921190', name: 'Other General Government Support'},
  {value: '922110', name: 'Courts'},
  {value: '922120', name: 'Police Protection'},
  {value: '922130', name: 'Legal Counsel and Prosecution'},
  {value: '922140', name: 'Correctional Institutions'},
  {value: '922150', name: 'Parole Offices and Probation Offices'},
  {value: '922160', name: 'Fire Protection'},
  {value: '922190', name: 'Other Justice, Public Order, and Safety Activities '},
  {value: '923110', name: 'Administration of Education Programs'},
  {value: '923120', name: 'Administration of Public Health Programs'},
  {value: '923130', name: 'Administration of Human Resource Programs (except Education, Public Health, and Veterans\' Affairs Programs)'},
  {value: '923140', name: 'Administration of Veterans\' Affairs'},
  {value: '924110', name: 'Administration of Air and Water Resource and Solid Waste Management Programs'},
  {value: '924120', name: 'Administration of Conservation Programs'},
  {value: '925110', name: 'Administration of Housing Programs'},
  {value: '925120', name: 'Administration of Urban Planning and Community and Rural Development'},
  {value: '926110', name: 'Administration of General Economic Programs'},
  {value: '926120', name: 'Regulation and Administration of Transportation Programs'},
  {value: '926130', name: 'Regulation and Administration of Communications, Electric, Gas, and Other Utilities '},
  {value: '926140', name: 'Regulation of Agricultural Marketing and Commodities'},
  {value: '926150', name: 'Regulation, Licensing, and Inspection of Miscellaneous Commercial Sectors '},
  {value: '927110', name: 'Space Research and Technology'},
  {value: '928110', name: 'National Security'},
  {value: '928120', name: 'International Affairs'}
];
